[2024-11-25T21:21:40.310+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-25T21:21:40.333+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_weather.extract_data manual__2024-11-25T21:19:50.427510+00:00 [queued]>
[2024-11-25T21:21:40.344+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_weather.extract_data manual__2024-11-25T21:19:50.427510+00:00 [queued]>
[2024-11-25T21:21:40.345+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 3
[2024-11-25T21:21:40.364+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_data> on 2024-11-25 21:19:50.427510+00:00
[2024-11-25T21:21:40.369+0000] {standard_task_runner.py:72} INFO - Started process 57 to run task
[2024-11-25T21:21:40.371+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_weather', 'extract_data', 'manual__2024-11-25T21:19:50.427510+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/extract_weather.py', '--cfg-path', '/tmp/tmpx5_t3ae6']
[2024-11-25T21:21:40.374+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask extract_data
[2024-11-25T21:21:40.395+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-25T21:21:40.443+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_weather.extract_data manual__2024-11-25T21:19:50.427510+00:00 [running]> on host 03f3e1ef676b
[2024-11-25T21:21:40.544+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_weather' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T21:19:50.427510+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-25T21:19:50.427510+00:00'
[2024-11-25T21:21:40.545+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-25T21:21:40.575+0000] {base.py:84} INFO - Retrieving connection 'weather_api'
[2024-11-25T21:21:41.252+0000] {extract_weather.py:26} INFO - Writing ratings to {'temp_c': -3.0, 'condition': 'Light snow'}
[2024-11-25T21:21:41.253+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-25T21:21:41.267+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-25T21:21:41.268+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=extract_weather, task_id=extract_data, run_id=manual__2024-11-25T21:19:50.427510+00:00, execution_date=20241125T211950, start_date=20241125T212140, end_date=20241125T212141
[2024-11-25T21:21:41.311+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-25T21:21:41.336+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-25T21:21:41.339+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
